#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
## Alias for checking the ssl certificate status
alias checkssl="openssl s_client -connect"

# Source platform specific customizations
if [ -f ~/.customize_zshrc ]; then
    source ~/.customize_zshrc
else
    print "404: ~/.customize_zshrc not found."
fi
